# Coolify deployment configuration for Appwrite
# Simplified version based on successful local testing

version: '3.8'

x-logging: &x-logging
  logging:
    driver: "json-file"
    options:
      max-file: "5"
      max-size: "10m"

services:
  appwrite:
    container_name: appwrite
    <<: *x-logging
    image: appwrite/appwrite:1.7.4
    networks:
      - appwrite
    volumes:
      - appwrite-uploads:/storage/uploads:rw
      - appwrite-imports:/storage/imports:rw
      - appwrite-cache:/storage/cache:rw
      - appwrite-config:/storage/config:rw
      - appwrite-certificates:/storage/certificates:rw
      - appwrite-functions:/storage/functions:rw
      - appwrite-sites:/storage/sites:rw
      - appwrite-builds:/storage/builds:rw
    depends_on:
      - mariadb
      - redis
    entrypoint:
      - php
      - -e
      - app/http.php
    environment:
      - _APP_ENV=production
      - _APP_EDITION=self-hosted
      - _APP_WORKER_PER_CORE=6
      - _APP_COMPRESSION_MIN_SIZE_BYTES=1024
      - _APP_CONSOLE_WHITELIST_ROOT=disabled
      - _APP_CONSOLE_WHITELIST_EMAILS=${_APP_CONSOLE_WHITELIST_EMAILS}
      - _APP_CONSOLE_SESSION_ALERTS=enabled
      - _APP_CONSOLE_WHITELIST_IPS=${_APP_CONSOLE_WHITELIST_IPS}
      - _APP_CONSOLE_COUNTRIES_DENYLIST=AQ
      - _APP_CONSOLE_HOSTNAMES=${_APP_CONSOLE_HOSTNAMES}
      - _APP_DOMAIN=${_APP_DOMAIN}
      - _APP_CONSOLE_DOMAIN=${_APP_CONSOLE_DOMAIN}
      - _APP_DOMAIN_FUNCTIONS=${_APP_DOMAIN_FUNCTIONS}
      - _APP_DOMAIN_SITES=${_APP_DOMAIN_SITES}
      - _APP_DOMAIN_TARGET_CNAME=${_APP_DOMAIN_TARGET_CNAME}
      - _APP_DOMAIN_TARGET_A=${_APP_DOMAIN_TARGET_A}
      - _APP_DOMAIN_TARGET_AAAA=${_APP_DOMAIN_TARGET_AAAA}
      - _APP_SYSTEM_EMAIL_NAME=${_APP_SYSTEM_EMAIL_NAME}
      - _APP_SYSTEM_EMAIL_ADDRESS=${_APP_SYSTEM_EMAIL_ADDRESS}
      - _APP_SYSTEM_TEAM_EMAIL=${_APP_SYSTEM_TEAM_EMAIL}
      - _APP_EMAIL_SECURITY=${_APP_EMAIL_SECURITY}
      - _APP_EMAIL_CERTIFICATES=${_APP_EMAIL_CERTIFICATES}
      - _APP_SYSTEM_RESPONSE_FORMAT=
      - _APP_CUSTOM_DOMAIN_DENY_LIST=
      - _APP_OPTIONS_ABUSE=disabled
      - _APP_OPTIONS_ROUTER_PROTECTION=disabled
      - _APP_OPTIONS_FORCE_HTTPS=${_APP_OPTIONS_FORCE_HTTPS}
      - _APP_OPTIONS_ROUTER_FORCE_HTTPS=${_APP_OPTIONS_ROUTER_FORCE_HTTPS}
      - _APP_OPENSSL_KEY_V1=${_APP_OPENSSL_KEY_V1}
      - _APP_RULES_FORMAT=md5
      - _APP_REDIS_HOST=redis
      - _APP_REDIS_PORT=6379
      - _APP_REDIS_PASS=${_APP_REDIS_PASS}
      - _APP_REDIS_USER=${_APP_REDIS_USER}
      - _APP_DB_HOST=mariadb
      - _APP_DB_PORT=3306
      - _APP_DB_SCHEMA=appwrite
      - _APP_DB_USER=${_APP_DB_USER}
      - _APP_DB_PASS=${_APP_DB_PASS}
      - _APP_DB_ROOT_PASS=${_APP_DB_ROOT_PASS}
      - _APP_STORAGE_DEVICE=${_APP_STORAGE_DEVICE}
      - _APP_STORAGE_ANTIVIRUS=disabled
      - _APP_STORAGE_ANTIVIRUS_HOST=clamav
      - _APP_STORAGE_ANTIVIRUS_PORT=3310
      - _APP_SMTP_HOST=${_APP_SMTP_HOST}
      - _APP_SMTP_PORT=${_APP_SMTP_PORT}
      - _APP_SMTP_SECURE=${_APP_SMTP_SECURE}
      - _APP_SMTP_USERNAME=${_APP_SMTP_USERNAME}
      - _APP_SMTP_PASSWORD=${_APP_SMTP_PASSWORD}
      - _APP_SMS_PROVIDER=${_APP_SMS_PROVIDER}
      - _APP_SMS_FROM=${_APP_SMS_FROM}
      - _APP_SMS_PROJECTS_DENY_LIST=${_APP_SMS_PROJECTS_DENY_LIST}
      - _APP_STORAGE_LIMIT=${_APP_STORAGE_LIMIT}
      - _APP_STORAGE_PREVIEW_LIMIT=${_APP_STORAGE_PREVIEW_LIMIT}
      - _APP_COMPUTE_SIZE_LIMIT=${_APP_COMPUTE_SIZE_LIMIT}
      - _APP_FUNCTIONS_TIMEOUT=${_APP_FUNCTIONS_TIMEOUT}
      - _APP_SITES_TIMEOUT=${_APP_SITES_TIMEOUT}
      - _APP_COMPUTE_BUILD_TIMEOUT=${_APP_COMPUTE_BUILD_TIMEOUT}
      - _APP_COMPUTE_CPUS=${_APP_COMPUTE_CPUS}
      - _APP_COMPUTE_MEMORY=${_APP_COMPUTE_MEMORY}
      - _APP_COMPUTE_INACTIVE_THRESHOLD=${_APP_COMPUTE_INACTIVE_THRESHOLD}
      - _APP_COMPUTE_MAINTENANCE_INTERVAL=${_APP_COMPUTE_MAINTENANCE_INTERVAL}
      - _APP_COMPUTE_RUNTIMES_NETWORK=runtimes
      - _APP_EXECUTOR_SECRET=${_APP_EXECUTOR_SECRET}
      - _APP_EXECUTOR_HOST=${_APP_EXECUTOR_HOST}
      - _APP_BROWSER_HOST=${_APP_BROWSER_HOST}
      - _APP_FUNCTIONS_RUNTIMES=${_APP_FUNCTIONS_RUNTIMES}
      - _APP_SITES_RUNTIMES=${_APP_SITES_RUNTIMES}
      - _APP_MAINTENANCE_INTERVAL=${_APP_MAINTENANCE_INTERVAL}
      - _APP_MAINTENANCE_START_TIME=${_APP_MAINTENANCE_START_TIME}
      - _APP_MAINTENANCE_RETENTION_CACHE=${_APP_MAINTENANCE_RETENTION_CACHE}
      - _APP_MAINTENANCE_RETENTION_EXECUTION=${_APP_MAINTENANCE_RETENTION_EXECUTION}
      - _APP_MAINTENANCE_RETENTION_ABUSE=${_APP_MAINTENANCE_RETENTION_ABUSE}
      - _APP_MAINTENANCE_RETENTION_AUDIT=${_APP_MAINTENANCE_RETENTION_AUDIT}
      - _APP_MAINTENANCE_RETENTION_AUDIT_CONSOLE=${_APP_MAINTENANCE_RETENTION_AUDIT_CONSOLE}
      - _APP_MAINTENANCE_RETENTION_USAGE_HOURLY=${_APP_MAINTENANCE_RETENTION_USAGE_HOURLY}
      - _APP_MAINTENANCE_RETENTION_SCHEDULES=${_APP_MAINTENANCE_RETENTION_SCHEDULES}
      - _APP_USAGE_AGGREGATION_INTERVAL=${_APP_USAGE_AGGREGATION_INTERVAL}
      - _APP_STATS_RESOURCES_INTERVAL=${_APP_STATS_RESOURCES_INTERVAL}
      - _APP_USAGE_STATS=${_APP_USAGE_STATS}
      - _APP_LOGGING_CONFIG=${_APP_LOGGING_CONFIG}
      - _APP_GRAPHQL_MAX_BATCH_SIZE=${_APP_GRAPHQL_MAX_BATCH_SIZE}
      - _APP_GRAPHQL_MAX_COMPLEXITY=${_APP_GRAPHQL_MAX_COMPLEXITY}
      - _APP_GRAPHQL_MAX_DEPTH=${_APP_GRAPHQL_MAX_DEPTH}
      - _APP_DOCKER_HUB_USERNAME=${_APP_DOCKER_HUB_USERNAME}
      - _APP_DOCKER_HUB_PASSWORD=${_APP_DOCKER_HUB_PASSWORD}
      - _APP_VCS_GITHUB_APP_NAME=${_APP_VCS_GITHUB_APP_NAME}
      - _APP_VCS_GITHUB_PRIVATE_KEY=${_APP_VCS_GITHUB_PRIVATE_KEY}
      - _APP_VCS_GITHUB_APP_ID=${_APP_VCS_GITHUB_APP_ID}
      - _APP_VCS_GITHUB_CLIENT_ID=${_APP_VCS_GITHUB_CLIENT_ID}
      - _APP_VCS_GITHUB_CLIENT_SECRET=${_APP_VCS_GITHUB_CLIENT_SECRET}
      - _APP_VCS_GITHUB_WEBHOOK_SECRET=${_APP_VCS_GITHUB_WEBHOOK_SECRET}
      - _APP_MIGRATIONS_FIREBASE_CLIENT_ID=${_APP_MIGRATIONS_FIREBASE_CLIENT_ID}
      - _APP_MIGRATIONS_FIREBASE_CLIENT_SECRET=${_APP_MIGRATIONS_FIREBASE_CLIENT_SECRET}
      - _APP_ASSISTANT_OPENAI_API_KEY=${_APP_ASSISTANT_OPENAI_API_KEY}
      - _APP_MESSAGE_SMS_TEST_DSN=${_APP_MESSAGE_SMS_TEST_DSN}
      - _APP_MESSAGE_EMAIL_TEST_DSN=${_APP_MESSAGE_EMAIL_TEST_DSN}
      - _APP_MESSAGE_PUSH_TEST_DSN=${_APP_MESSAGE_PUSH_TEST_DSN}
      - _APP_WEBHOOK_MAX_FAILED_ATTEMPTS=${_APP_WEBHOOK_MAX_FAILED_ATTEMPTS}
      - _APP_PROJECT_REGIONS=${_APP_PROJECT_REGIONS}
      - _APP_FUNCTIONS_CREATION_ABUSE_LIMIT=${_APP_FUNCTIONS_CREATION_ABUSE_LIMIT}
      - _APP_STATS_USAGE_DUAL_WRITING_DBS=${_APP_STATS_USAGE_DUAL_WRITING_DBS}

  mariadb:
    image: mariadb:10.11
    container_name: appwrite-mariadb
    <<: *x-logging
    networks:
      - appwrite
    volumes:
      - appwrite-mariadb:/var/lib/mysql:rw
    environment:
      - MYSQL_ROOT_PASSWORD=${_APP_DB_ROOT_PASS}
      - MYSQL_DATABASE=appwrite
      - MYSQL_USER=${_APP_DB_USER}
      - MYSQL_PASSWORD=${_APP_DB_PASS}
      - MARIADB_AUTO_UPGRADE=1
    command: "mysqld --innodb-flush-method=fsync"

  redis:
    image: redis:7.2.4-alpine
    <<: *x-logging
    container_name: appwrite-redis
    command: >
      redis-server
      --maxmemory            512mb
      --maxmemory-policy     allkeys-lru
      --maxmemory-samples    5
    networks:
      - appwrite
    volumes:
      - appwrite-redis:/data:rw

networks:
  appwrite:
    name: appwrite

volumes:
  appwrite-mariadb:
  appwrite-redis:
  appwrite-cache:
  appwrite-uploads:
  appwrite-imports:
  appwrite-certificates:
  appwrite-functions:
  appwrite-sites:
  appwrite-builds:
  appwrite-config: